# This file is autogenerated. Instead of editing this file, please use the
# migrations feature of ActiveRecord to incrementally modify your database, and
# then regenerate this schema definition.

ActiveRecord::Schema.define(:version => 3) do

  create_table "divisions", :force => true do |t|
    t.column "description", :string,   :default => "", :null => false
    t.column "created_at",  :datetime
    t.column "updated_at",  :datetime
  end

  create_table "games", :force => true do |t|
    t.column "teamh_id",    :integer
    t.column "teama_id",    :integer
    t.column "date_played", :datetime
    t.column "Q1H",         :integer
    t.column "Q1A",         :integer
    t.column "Q2H",         :integer
    t.column "Q2A",         :integer
    t.column "Q3H",         :integer
    t.column "Q3A",         :integer
    t.column "Q4H",         :integer
    t.column "Q4A",         :integer
    t.column "E1H",         :integer
    t.column "E1A",         :integer
    t.column "E2H",         :integer
    t.column "E2A",         :integer
    t.column "E3H",         :integer
    t.column "E3A",         :integer
    t.column "FTH",         :integer
    t.column "FTA",         :integer
    t.column "created_at",  :datetime
    t.column "updated_at",  :datetime
  end

  create_table "players", :force => true do |t|
    t.column "team_id",    :integer,  :null => false
    t.column "first_name", :string
    t.column "surname",    :string
    t.column "nickname",   :string
    t.column "shirt_no",   :integer
    t.column "dob",        :date
    t.column "address",    :string
    t.column "email",      :string
    t.column "contact_no", :string
    t.column "created_at", :datetime
    t.column "updated_at", :datetime
  end

  create_table "seasons", :force => true do |t|
    t.column "description", :string,   :default => "", :null => false
    t.column "created_at",  :datetime
    t.column "updated_at",  :datetime
  end

  create_table "stats", :force => true do |t|
    t.column "game_id",    :integer,  :null => false
    t.column "player_id",  :integer,  :null => false
    t.column "PS_1",       :integer
    t.column "PM_1",       :integer
    t.column "PS_2",       :integer
    t.column "PM_2",       :integer
    t.column "PS_3",       :integer
    t.column "PM_3",       :integer
    t.column "Min_Played", :integer
    t.column "Fouls_Com",  :integer
    t.column "Of_Reb",     :integer
    t.column "Def_Reb",    :integer
    t.column "Steals",     :integer
    t.column "Blocks",     :integer
    t.column "Mistakes",   :integer
    t.column "Assists",    :integer
    t.column "created_at", :datetime
    t.column "updated_at", :datetime
  end

  create_table "teams", :force => true do |t|
    t.column "name",        :string,   :default => "", :null => false
    t.column "division_id", :integer,                  :null => false
    t.column "season_id",   :integer,                  :null => false
    t.column "game_day",    :string
    t.column "game_time",   :time
    t.column "kit_a",       :string
    t.column "kit_b",       :string
    t.column "address",     :string
    t.column "directions",  :string
    t.column "url",         :string
    t.column "created_at",  :datetime
    t.column "updated_at",  :datetime
  end

end
